config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'topics#index'
  resources :topics do
    resources :posts do
      resources :comments, only: [:create, :destroy] do
        resources :user_comment_ratings, only: [:create, :index]
      end
      resources :ratings, only: [:create]
      member do
        post :mark_as_read
      end
    end
  end

  resources :posts, only: [:index]
  resources :tags
  resource :user, only: [:edit, :update], controller: 'users'
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  before_validation :normalize_name

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  private

  def normalize_name
    self.name = name.to_s.strip.downcase
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]

  def index
    @tags = Tag.order(:name)
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path, notice: "Tag created successfully."
    else
      render :new
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: "Tag updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to tags_path, notice: "Tag deleted successfully."
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/views/tags/_form.html.erb
<%= form_with model: tag, local: true, html: { class: "needs-validation" } do |f| %>
  <% if tag.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h5 class="alert-heading"><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h5>
      <ul class="mb-0">
        <% tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6 mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, autofocus: true, class: "form-control #{'is-invalid' if tag.errors[:name].any?}" %>
      <% if tag.errors[:name].any? %>
        <div class="invalid-feedback">
          <%= tag.errors[:name].join(", ") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tags/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Edit Tag</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= render "form", tag: @tag %>
  </div>
</div>

<div class="row mt-3">
  <div class="col-md-12">
    <%= link_to "Back to Tags", tags_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/tags/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Tags</h1>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <%= link_to "New Tag", new_tag_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @tags.any? %>
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead class="table-dark">
            <tr>
              <th>Name</th>
              <th>Posts</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @tags.each do |tag| %>
              <tr>
                <td><%= tag.name %></td>
                <td><%= tag.posts.count %></td>
                <td>
                  <%= link_to "Edit", edit_tag_path(tag), class: "btn btn-sm btn-outline-primary" %>
                  <%= link_to "Delete", tag_path(tag), method: :delete, data: { confirm: "Delete this tag?" }, class: "btn btn-sm btn-outline-danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <div class="alert alert-info">
        No tags yet. Create the first one!
      </div>
    <% end %>
  </div>
</div>

app/views/tags/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>New Tag</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= render "form", tag: @tag %>
  </div>
</div>

<div class="row mt-3">
  <div class="col-md-12">
    <%= link_to "Back to Tags", tags_path, class: "btn btn-secondary" %>
  </div>
</div>