config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'topics#index'
  resources :topics do
    resources :posts do
      resources :comments, only: [:create, :destroy] do
        resources :user_comment_ratings, only: [:create, :index]
      end
      resources :ratings, only: [:create]
      member do
        post :mark_as_read
      end
    end
  end

  resources :posts, only: [:index]
  resources :tags
  resource :user, only: [:edit, :update], controller: 'users'
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ror04</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Bootstrap JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- Bootstrap Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <%= link_to "Ror04", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to "Topics", topics_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "All Posts", posts_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Tags", tags_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <span class="navbar-text me-3">
                  Logged in as: <strong><%= current_user.email %></strong>
                </span>
              </li>
              <li class="nav-item me-2">
                <button type="button" class="btn btn-outline-light btn-sm" data-bs-toggle="modal" data-bs-target="#editProfileModal">
                  Edit Profile
                </button>
              </li>
              <li class="nav-item">
                <%= button_to 'Sign out',
                              destroy_user_session_path,
                              method: :delete,
                              class: "btn btn-outline-light btn-sm",
                              form: { style: 'display:inline' } %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Bootstrap Alerts -->
    <div class="container-fluid mt-3">
      <% if notice %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <!-- Edit Profile Modal -->
    <% if user_signed_in? %>
      <%= render 'users/edit_modal', user: current_user %>
    <% end %>

    <script>
      // Auto-open modal if there are profile errors
      <% if flash[:open_modal] == 'editProfileModal' %>
        document.addEventListener('DOMContentLoaded', function() {
          var modal = new bootstrap.Modal(document.getElementById('editProfileModal'));
          modal.show();
        });
      <% end %>
    </script>
  </body>
</html>